apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-configmap
data:
    init.sql: |-
        CREATE DATABASE IF NOT EXISTS `authdb`;
        CREATE DATABASE IF NOT EXISTS `users`;
    database_url: jdbc:mysql://mysql-service/authdb
