server:
    port: 8083
spring:
    datasource:
        url: jdbc:h2:mem:virtual
        username: root
        password: root
        driverClassName: org.h2.Driver
#    datasource:
#        url: "jdbc:mysql://localhost:3306/4energy"
#        username: "root"
#        password: "root"
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
    application:
        name: AUTHENTICATIONAPI
    h2:
        console.enabled: true
        console.path: /h2-console
        console.settings.trace: false
        spring.h2.console.settings.web-allow-others: false
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
