server:
    port: 8082
spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  application:
    name: AuthenticationAPI
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost:3307/4energy_auth_service"
    username: "root"
    password: "root"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka