server:
    port: 8083
spring:
    datasource:
        url: "jdbc:mysql://localhost:3307/test"
        username: "root"
        password: "root"
#    jpa:
#        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#        generate-ddl: true
#        hibernate:
#            ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

# Changed to h2 for the GitHub CI(Change back when working locally, if you want)
#      datasource:
#        url: "jdbc:mysql://localhost:3306/test"
#        username: "root"
#        password:
