server:
    port: 8081
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: "root"
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka