server:
    port: 8082
spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  application:
    name: AuthenticationAPI

  datasource:
    url: "jdbc:h2:mem:virtual"
    username: "sa"
    password: "password"
    jpa:
      hibernate:
        ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#
#      datasource:
#        url: "jdbc:h2:mem:virtual"
#        username: "sa"
#        password: "password"
#        jpa:
#          hibernate:
#            ddl-auto: update